---
title: "The Evolution of Basketball"
description: |
  An analysis about the noticeable trends in the history of basketball...
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

library(tidyverse)
library(RSQLite)
library(rgeos)
library(dplyr)
library(sf)
library(rvest)
library(stringr)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggthemes)

world <- ne_countries(scale = "medium", returnclass = "sf")

sqlite <- dbDriver("SQLite")
basketball_database <- dbConnect(sqlite, "basketball_data/basketball.sqlite")
games_data <- tbl(basketball_database, "Game")
team_salary_data <- tbl(basketball_database, "Team_Salary")
player_salary_data <- tbl(basketball_database, "Player_Salary")
player_data <- tbl(basketball_database, "Player")
draft_combine_data <- tbl(basketball_database, "Draft_Combine")

player_map_data <- read.csv("players_map.csv")
sports_league_revenue_data <- read.csv("sportsLeagueRevenue/Data-Table 1.csv")
league_averages_data <- read.csv("league_averages.csv")

```

```{r, include=TRUE, echo=FALSE}
nba_viewership_clean <- read_html("https://en.wikipedia.org/wiki/NBA_Finals_television_ratings") %>% 
  html_elements("table tbody tr") %>% 
  html_text2() %>% 
  as_tibble() %>% 
  slice(7:38) %>% 
  mutate(value = str_replace_all(value, "\n", ""),
         value = str_replace_all(value, "\t", "")) %>% 
  mutate(year = as.double(str_sub(value, 1, 4)),
         network = str_sub(value, 5, 7),
         value = str_sub(value, 8, str_length(value))) %>% 
  mutate(viewership = as.character(stringr::str_extract(string = value,
                                               pattern = "(?<=\\().*(?=\\))"))) %>% 
  mutate(viewership = as.double(str_sub(viewership, 1, 4))) %>% 
  ggplot(mapping = aes(year, viewership, color = network)) +
  geom_line() + 
  theme_economist() + 
  labs(title = "Average Viewership for NBA Finals Series Over Time",
       subtitle = "put subtitle here",
       x = "Year (1987 to 2018)",
       y = "Average Viewership in Millions",
       caption = "Source: Wikipedia (2021)")

# 1987-2020 is what we want
nba_viewership_clean
```

```{r, include=TRUE, echo=FALSE}
league_averages_rebounds <- league_averages_data %>% 
  rename(Season = "X.1") %>% 
  rename(ORB = "X.14") %>% 
  rename(DRB = "X.15") %>% 
  rename(TRB = "X.16") %>% 
  select(Season, ORB, DRB, TRB) %>% 
  slice(2:76) %>% 
  mutate(Season = as.double(str_sub(Season, 1, 4)),
         ORB = as.double(ORB),
         DRB = as.double(DRB),
         TRB = as.double(TRB)) %>% 
  drop_na(Season, ORB, DRB, TRB) %>% 
  pivot_longer(names_to = "rebound_rate",
               values_to = "rpg",
               cols = -Season) %>% 
  ggplot(mapping = aes(Season, rpg, color = rebound_rate)) + 
  geom_line() + 
  theme_minimal() + 
  labs(title = "Different Average League Rebound Rates Over Time",
       subtitle = "put subtitle here",
       x = "Season",
       y = "Average Rebounds Per Game",
       caption = "Source: Basketball Reference (2021)")

league_averages_rebounds
```


```{r, include=TRUE, echo=FALSE}
three_point_data <- games_data %>% 
  select(GAME_DATE, FG3M_HOME, PTS_HOME) %>%
  mutate(YEAR = as.double(str_sub(GAME_DATE, 1, 4))) %>% 
  filter(FG3M_HOME != "<NA>" && YEAR >= 1979) %>% 
  mutate(FG3M_HOME = as.double(FG3M_HOME)) %>% 
  mutate(PTS_PCT_3P = (FG3M_HOME * 3) / PTS_HOME) %>% 
  ggplot(mapping = aes(YEAR, PTS_PCT_3P)) + 
  geom_jitter(alpha = 0.1, width = 2, color = "lightblue") + 
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = TRUE) + 
  theme_dark() + 
  labs(title = "Percentage of Points from 3-Pointers by Home Teams Over Time",
       subtitle = "The positive trend indicates that home teams have been more likely to get points from \nthree-point shots since the introduction of the 3-point line in 1979",
       x = "Year (1979 to 2021)",
       y = "% of Points from 3-Pointers",
       caption = "Source: NBA Advanced Stats (2021)")

three_point_data
```

```{r, include=TRUE, echo=FALSE, out.width="90%"}
sports_league_revenue_clean <- sports_league_revenue_data %>% 
  select(X.2, X.3, X.4, X.5) %>% 
  rename(NFL = "X.2") %>% 
  rename(MLB = "X.3") %>% 
  rename(NBA = "X.4") %>% 
  rename(NHL = "X.5") %>% 
  slice(5:18) %>% 
  mutate(Year = 1:n() + 2006) %>% 
  pivot_longer(names_to = "League",
               values_to = "Revenue",
               cols = -Year) %>% 
  mutate(Revenue = as.double(Revenue)) %>% 
  ggplot(mapping = aes(Year, Revenue, color = League)) + 
  geom_line() + 
  theme_classic() + 
  scale_color_discrete(name = "League", labels = c("Major League Baseball",
                                                   "National Basketball Association",
                                                   "National Football League",
                                                   "National Hockey League")) + 
  labs(title = "Average Franchise Value of Major American Sports Leagues Over Time",
       subtitle = "With the recent overtake of the MLB, it is easy to see how the valuation of the NBA has \nrisen significantly since 2007",
       x = "Year (2007 to 2020)",
       y = "Average Franchise Value in Millions (USD)",
       caption = "Source: Statista; Forbes (2021)")


sports_league_revenue_clean
```


```{r, include=TRUE, echo=FALSE}

```
player_birthplace_data <- player_map_data %>% 
  select(birthPlace) %>% 
  drop_na(birthPlace) %>% 
  mutate(birthPlace = as.factor(birthPlace)) %>% 
  group_by(birthPlace) %>% 
  summarize(total = n())
  
ggplot(data = player_birthplace_data) + 
  geom_sf(aes(fill = birthPlace))
  
player_birthplace_data

```{r, include=TRUE, echo=FALSE}
current_player_salary_data <- player_salary_data %>% 
  filter(slugSeason == "2020-21") %>% 
  select(slugSeason, value, nameTeam, namePlayer) %>% 
  ggplot(mapping = aes(value)) + 
  geom_density()

current_player_salary_data
```

